AP_SLOT_DATA_MAPPING = {
    ["required_artifacts"] = {
        ["name"] = "RequiredArtifacts",
        ["offset"] = -1,
        ["default"] = 11
    },
    ["final_bosses"] = "FinalBoss",
    ["missile_launcher"] = "MainMissile",
    ["main_power_bomb"] = "MainPowerBomb",
    ["non_varia_heat_damage"] = "NonVariaHeatDamage",
    ["remove_hive_mecha"] = "RemoveHiveMecha",
    ["trick_difficulty"] = {
        ["name"] = "Tricks",
        ["offset"] = 1
    },
    ["backwards_lower_mines"] = "BackwardsLowerMines",
    ["flaahgra_power_bombs"] = "FlaahgraPowerBombs",
    ["remove_xray_requirements"] = "RemoveXRayRequirements",
    ["remove_thermal_requirements"] = "RemoveThermalRequirements",
    ["starting_room_name"] = {
        ["name"] = "StartingRoom",
        ["mapping"] = {
            ["Landing Site"] = 0,
            ["Arboretum"] = 1,
            ["Burn Dome Access"] = 2,
            ["Ruined Fountain"] = 3,
            ["Save Station 1"] = 4,
            ["Save Station 2"] = 5,
            ["Tower Chamber"] = 6,
            ["Warrior Shrine"] = 7,
            ["East Tower"] = 8,
            ["Save Station B"] = 9,
            ["Arbor Chamber"] = 10,
            ["Transport to Chozo Ruins East"] = 11,
            ["Quarantine Monitor"] = 12,
            ["Sunchamber Lobby"] = 13,
        },
    },
    ["progressive_beam_upgrades"] = "ProgressiveBeams",
    ["combat_logic_difficulty"] = "CombatLogic",
    ["elevator_randomization"] = "ElevatorsRandom",
    ["door_color_randomization"] = "DoorRando",
    ["blast_shield_randomization"] = "BlastShieldRando",
    ["pre_scan_elevators"] = "PreScanElevators",
}
