AP_TRICKS = {
    TrickItem("Early Artifact of Wild", nil, { "EarlyWild" }),
    TrickItem("Alcove Escape", TrickDifficulty.EASY, { "alcove_escape" }),
    TrickItem("Landing Site Scan Dash", TrickDifficulty.EASY, { "landing_site_scan_dash" }),
    TrickItem("Frigate No Gravity", TrickDifficulty.EASY, { "frigate_no_gravity", "frigate_backwards_no_gravity" }),
    TrickItem("Hydro Access Tunnel No Gravity", TrickDifficulty.HARD, { "hydro_access_tunnel_no_gravity" }),
    TrickItem("Crashed Frigate Scan Dash", TrickDifficulty.HARD, { "frigate_crash_site_scan_dash" }),
    TrickItem("Crashed Frigate Slope Jump", TrickDifficulty.EASY, { "frigate_crash_site_slope_jump" }),
    TrickItem("Crashed Frigate Slope Jump No Space Jump", TrickDifficulty.MEDIUM, { "frigate_crash_site_slope_jump_no_sjb" }),
    TrickItem("Crashed Frigate Climb to Overgrown Cavern", TrickDifficulty.MEDIUM, { "frigate_crash_site_climb_to_overgrown_cavern" }),
    TrickItem("Great Tree Hall Skip Bars", TrickDifficulty.HARD, { "great_tree_hall_skip_bars" }),
    TrickItem("Great Tree Chamber No XRay", TrickDifficulty.EASY, { "great_tree_chamber_no_xray" }),
    TrickItem("Great Tree Chamber no Space Jump no XRay", TrickDifficulty.MEDIUM, { "great_tree_chamber_nsj_no_xray" }),
    TrickItem("Great Tree Hall No Spider Ball", TrickDifficulty.EASY, { "great_tree_hall_no_spider_ball" }),
    TrickItem("Root Cave Arbor Chamber No Grapple XRay", TrickDifficulty.HARD, { "root_cave_arbor_chamber_no_grapple_xray" }),
    TrickItem("Vault Via Plaza", TrickDifficulty.EASY, { "vault_via_plaza" }),
    TrickItem("Plaza Half Pipe No Boost", TrickDifficulty.EASY, { "plaza_half_pipe_no_boost" }),
    TrickItem("Plaza Half Pipe with only Morph Ball", TrickDifficulty.HARD, { "plaza_half_pipe_morph_only" }),
    TrickItem("Plaza Grapple Ledge R Jump", TrickDifficulty.EASY, { "plaza_grapple_ledge_r_jump" }),
    TrickItem("Plaza Grapple Ledge Tree Grapple", TrickDifficulty.EASY, { "plaza_grapple_ledge_tree_grapple" }),
    TrickItem("Ruined Shrine Upper Door L Jump", TrickDifficulty.EASY, { "ruined_shrine_upper_door_no_spider_ball" }),
    TrickItem("Ruined Shrine Upper Door Scan Dash", TrickDifficulty.HARD, { "ruined_shrine_upper_door_scan_dash" }),
    TrickItem("Ruined Shrine Scan Dash Escape", TrickDifficulty.EASY, { "ruined_shrine_scan_dash_escape" }),
    TrickItem("Tower of Light Climb Without Missiles", TrickDifficulty.EASY, { "tower_of_light_climb_without_missiles" }),
    TrickItem("Tower of Light Climb No Space Jump", TrickDifficulty.HARD, { "tower_of_light_climb_nsj" }),
    TrickItem("Tower Chamber No Gravity", TrickDifficulty.EASY, { "tower_chamber_no_gravity" }),
    TrickItem("Tower Chamber No Space Jump", TrickDifficulty.EASY, { "tower_chamber_no_space_jump" }),
    TrickItem("Ruined Nursery No Bombs", TrickDifficulty.HARD, { "ruined_nursery_no_bombs" }),
    TrickItem("Cross Magma Pool Suitless", TrickDifficulty.MEDIUM, { "magma_pool_scan_dash" }),
    TrickItem("Cross Magma Pool With SJB and Gravity", TrickDifficulty.EASY, { "magma_pool_debris_jump" }),
    TrickItem("Magma Pool Debris Jump", TrickDifficulty.EASY, { "magma_pool_item_debris_jump" }),
    TrickItem("Magma Pool Item No Grapple", TrickDifficulty.MEDIUM, { "magma_pool_item_scan_dash" }),
    TrickItem("Magma Pool Item Infinite Speed", TrickDifficulty.MEDIUM, { "magma_pool_item_infinite_speed" }),
    TrickItem("Arboretum Scan Gate Skip", TrickDifficulty.EASY, { "arboretum_scan_gate_skip" }),
    TrickItem("Gathering Hall Without Space Jump", TrickDifficulty.EASY, { "gathering_hall_without_space_jump" }),
    TrickItem("Watery Hall No Gravity", TrickDifficulty.EASY, { "watery_hall_no_gravity" }),
    TrickItem("Watery Hall No Gravity No Space Jump", TrickDifficulty.MEDIUM, { "watery_hall_no_gravity_no_space_jump" }),
    TrickItem("Furnace No Spider Ball", TrickDifficulty.EASY, { "furnace_no_spider_ball" }),
    TrickItem("Furnace Spider Track HBJ", TrickDifficulty.MEDIUM, { "furnace_spider_track_hbj" }),
    TrickItem("Furnace Spider Track SJ Bombs/Spring Ball", TrickDifficulty.MEDIUM, { "furnace_spider_track_sj_bombs_spring_ball" }),
    TrickItem("Crossway Item Fewer Reqs", TrickDifficulty.EASY, { "crossway_item_fewer_reqs" }),
    TrickItem("Crossway Half pipe bomb jump", TrickDifficulty.HARD, { "crossway_hpbj" }),
    TrickItem("Hall of Elders No Spider Ball", TrickDifficulty.EASY, { "hall_of_elders_bomb_slots_no_spider" }),
    TrickItem("Hall of Elders Reflecting Pool No Spider Ball", TrickDifficulty.EASY, { "hall_of_elders_reflecting_pool_no_spider" }),
    TrickItem("Hall of Elders Reflecting Pool No Wave Beam", TrickDifficulty.MEDIUM, { "hall_of_elders_reflecting_pool_no_wave_beam" }),
    TrickItem("Hall of Elders Elder Chamber No Spider Ball", TrickDifficulty.EASY, { "hall_of_elders_elder_chamber_no_spider" }),
    TrickItem("Hall of Elders Item No Spider Ball", TrickDifficulty.EASY, { "hall_of_elders_item_no_spider" }),
    TrickItem("Reflecting Pool Space Jump Climb", TrickDifficulty.EASY, { "reflecting_pool_space_jump_climb" }),
    TrickItem("Reflecting Pool No Space Jump Climb", TrickDifficulty.HARD, { "reflecting_pool_nsj_climb" }),
    TrickItem("Lava Lake Item Suitless", TrickDifficulty.MEDIUM, { "lava_lake_item_suitless" }),
    TrickItem("Lava Lake Item Missiles Only", TrickDifficulty.EASY, { "lava_lake_item_missiles_only" }),
    TrickItem("Triclops Pit Item No SJ", TrickDifficulty.MEDIUM, { "triclops_pit_item_no_sj" }),
    TrickItem("Triclops Pit Item No XRay", TrickDifficulty.MEDIUM, { "triclops_pit_item_no_xray" }),
    TrickItem("Triclops Pit Item No SJ No XRay", TrickDifficulty.MEDIUM, { "triclops_pit_item_no_sj_no_xray" }),
    TrickItem("Triclops Pit Item No Missiles", TrickDifficulty.EASY, { "triclops_pit_item_no_missiles" }),
    TrickItem("Warrior Shrine No Boost", TrickDifficulty.EASY, { "warrior_shrine_no_boost" }),
    TrickItem("Warrior Shrine Scan Only", TrickDifficulty.MEDIUM, { "warrior_shrine_scan_only" }),
    TrickItem("Warrior Shrine No Items", TrickDifficulty.MEDIUM, { "warrior_shrine_no_items" }),
    TrickItem("Shore Tunnel Escape No SJ", TrickDifficulty.MEDIUM, { "shore_tunnel_escape_no_sj" }),
    TrickItem("Fiery Shores Morphball Track SJ", TrickDifficulty.EASY, { "fiery_shores_morphball_track_sj" }),
    TrickItem("Transport Tunnel B Damage Boost", TrickDifficulty.EASY, { "transport_tunnel_b_damage_boost" }),
    TrickItem("Twin Fires Tunnel No Spider Ball", TrickDifficulty.MEDIUM, { "twin_fires_tunnel_no_spider" }),
    TrickItem("Cross Twin Fires Suitless", TrickDifficulty.MEDIUM, { "cross_twin_fires_suitless" }),
    TrickItem("Geothermal Core No Grapple Spider", TrickDifficulty.MEDIUM, { "geothermal_core_no_grapple_spider" }),
    TrickItem("Magmoor Workstation No Thermal", TrickDifficulty.EASY, { "magmoor_workstation_no_thermal" }),
    TrickItem("Ice Temple No SJ", TrickDifficulty.MEDIUM, { "ice_temple_no_sj" }),
    TrickItem("Ice Temple to chapel No SJ", TrickDifficulty.MEDIUM, { "ice_temple_to_chapel_no_sj" }),
    TrickItem("Shorelines Spider Track No SJ", TrickDifficulty.MEDIUM, { "shorelines_spider_track_no_sj" }),
    TrickItem("Ice Temple Item No SJ", TrickDifficulty.MEDIUM, { "ice_temple_item_no_sj" }),
    TrickItem("Chapel of Elders Escape No SJ", TrickDifficulty.MEDIUM, { "chapel_of_elders_escape_no_sj" }),
    TrickItem("Phendrana Canyon Escape No Items", TrickDifficulty.EASY, { "phendrana_canyon_escape_no_items" }),
    TrickItem("Phendrana Courtyard No Boost Spider", TrickDifficulty.EASY, { "phendrana_courtyard_no_boost_spider", "phendrana_courtyard_item_no_boost_spider" }),
    TrickItem("Phendrana Courtyard Quarantine Access No Boost Spider", TrickDifficulty.EASY, { "phendrana_courtyard_quarantine_access_no_boost_spider" }),
    TrickItem("Research Lab Aether Upper Item with DBJ", TrickDifficulty.EASY, { "research_lab_aether_item_dbj" }),
    TrickItem("Control Tower Item No Plasma", TrickDifficulty.EASY, { "control_tower_item_no_plasma" }),
    TrickItem("Monitor Cave No Grapple", TrickDifficulty.MEDIUM, { "monitor_cave_no_grapple" }),
    TrickItem("Quarantine to North Courtyard Slope Jump", TrickDifficulty.MEDIUM, { "quarantine_to_north_courtyard_slope_jump" }),
    TrickItem("Observatory Puzzle Skip", TrickDifficulty.MEDIUM, { "observatory_puzzle_skip" }),
    TrickItem("Frozen Pike No Bombs", TrickDifficulty.MEDIUM, { "frozen_pike_no_bombs" }),
    TrickItem("Frozen Pike No Gravity Suit", TrickDifficulty.MEDIUM, { "frozen_pike_no_gravity_suit" }),
    TrickItem("Frost Cave No Grapple", TrickDifficulty.EASY, { "frost_cave_no_grapple" }),
    TrickItem("Phendrana's Edge Storage Cavern No Grapple", TrickDifficulty.EASY, { "phendranas_edge_storage_cavern_no_grapple" }),
    TrickItem("Phendrana's Edge Security Cavern No Grapple", TrickDifficulty.EASY, { "phendranas_edge_security_cavern_no_grapple" }),
    TrickItem("Hunter Cave No Grapple", TrickDifficulty.EASY, { "hunter_cave_no_grapple" }),
    TrickItem("Gravity Chamber No Grapple Plasma", TrickDifficulty.MEDIUM, { "gravity_chamber_no_grapple_plasma" }),
    TrickItem("Main Quarry Item No Spider Ball", TrickDifficulty.MEDIUM, { "main_quarry_item_no_spider" }),
    TrickItem("Main Quarry to Waste Disposal No Grapple", TrickDifficulty.EASY, { "main_quarry_to_waste_disposal_no_grapple" }),
    TrickItem("Ore Processing Climb to Storage No Grapple Spider", TrickDifficulty.EASY, { "ore_processing_to_storage_depot_b_no_spider" }),
    TrickItem("Ore Processing Climb No Grapple Spider", TrickDifficulty.EASY, { "ore_processing_climb_no_grapple_spider" }),
    TrickItem("Mines Climb Shafts No Spider Ball", TrickDifficulty.HARD, { "mines_climb_shafts_no_spider" }),
    TrickItem("Elite Research laser No Boost", TrickDifficulty.EASY, { "elite_research_spinner_no_boost" }),
    TrickItem("Elite Research Backwards Wall Boost", TrickDifficulty.EASY, { "elite_research_backwards_wall_boost" }),
    TrickItem("Elite Research Backwards Wall Boost No Spider", TrickDifficulty.HARD, { "elite_research_backwards_wall_boost_no_spider" }),
    TrickItem("Ventilation Shaft HPBJ", TrickDifficulty.HARD, { "ventilation_shaft_hpbj" }),
    TrickItem("Metroid Quarantine A No Spider Ball", TrickDifficulty.MEDIUM, { "metroid_quarantine_a_no_spider" }),
    TrickItem("Fungal Hall Access No Phazon Suit", TrickDifficulty.EASY, { "fungal_hall_access_no_phazon_suit" }),
    TrickItem("Fungal Hall A No Grapple", TrickDifficulty.MEDIUM, { "fungal_hall_a_no_grapple" }),
    TrickItem("Fungal Hall B No Grapple", TrickDifficulty.MEDIUM, { "fungal_hall_b_no_grapple" }),
    TrickItem("Metroid Quarantine B No Spider Grapple", TrickDifficulty.MEDIUM, { "metroid_quarantine_b_no_spider_grapple" }),
    TrickItem("Phazon Processing Center Item No Spider Ball", TrickDifficulty.EASY, { "phazon_processing_center_item_no_spider" }),
    TrickItem("Phazon Processing Center No Phazon Suit", TrickDifficulty.EASY, { "phazon_processing_center_no_phazon_suit" }),
    TrickItem("Phazon Processing Center No Spider Ball", TrickDifficulty.EASY, { "climb_phazon_processing_center_no_spider" }),
}
