line-length = 120
indent-width = 4

[lint]
select = [
    "B",
    "C",
    "E",
    "F",
    "W",
    "I",
    "N",
    "Q",
    "UP",
    "RET",
    "RSE",
    "RUF",
    "ISC",
    "PLC",
    "PLE",
    "PLW",
    "T20",
    "PERF",
]
ignore = [
    "C901",    # Author disagrees with limiting branch complexity
    "PLC1802", # Author agrees with this rule, but it literally changes the functionality of the code, which is unsafe.
    "PLC1901", # This is just not equivalent
    "UP015",   # Explicit is better than implicit, so we'd prefer to keep "r" in open() calls.
]
